for pair in BTCUSDT ETHUSDT BNBUSDT ADAUSDT XRPUSDT COCOSUSDT THETAUSDT LTCUSDT LINKUSDT BCHUSDT DOTUSDT FILUSDT ONEUSDT CHZUSDT XLMUSDT DOGEUSDT VETUSDT XVSUSDT TRXUSDT ATOMUSDT FTTUSDT HOTUSDT BTTUSDT OCEANUSDT ANKRUSDT
do
    node bot.js ${pair}
done;